### ISSUE TITLE
Creating top-level directories

### ISSUE THREAD

**Issue by lights0123** [Vogtinator/libnspire#2]
The official Link Software supports creating top-level directories. However, with both fuse-nspire and calling the library directly, an error occurs when attempting to create a directory that's not in another directory.

**Comment by Vogtinator** [comment]
Could reproduce on CX II. It works fine in firebird, but with libnspire and real hardware it fails with

```
20:25:12.020,20-09-30,0000014706,SYNC8000,syncServiceOperationCallback(): [100.1:SYNC::100.0:0x8000]: SYNC service handler(Max Pkt=1440) is STARTING
20:25:12.020,20-09-30,0000014706,SYNC8000,syncServiceOperationCallback(): [100.1:SYNC::100.0:0x8000] -> MKDIR_CMD(0x000a)
20:25:12.020,20-09-30,0000014706,SYNC8000,syncServiceOperationCallback(): [100.1:SYNC::100.0:0x8000]: MKDIR_CMD: ParseVarRqst failed: <-273>
```

**Comment by Vogtinator** [comment]
It only failed because `/ndless` was shorter than 8 characters...
